
[server]
port = 5000
address = "0.0.0.0"
maxUploadSize = 200
enableCORS = false
headless = true

[theme]
primaryColor = "#1FB2A6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
